### PR TITLE
Move ruplacer formula here

### PR DESCRIPTION
**Pull request by dmerejkowsky**
Taken from:
  https://github.com/dmerejkowsky/homebrew-repo
at commit:
  65efce9add5c2e9be5797765185959be35c049b4

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
Original patch by @maximerety

**Comment by dmerejkowsky** [comment]
OK, turned out I misread homebrew doc :(

**Comment by maximerety** [comment]
@dmerejkowsky It wasn't necessarily a bad idea to move the ruplacer formula "somewhere else" though, as the current https://github.com/dmerejkowsky/homebrew-repo repo does not seem to follow the usual conventions.

Here's what we could do:

* Rename the `dmerejkowsky/homebrew-repo` repo into `dmerejkowsky/homebrew-ruplacer`
* Fix the readme in `dmerejkowsky/homebrew-ruplacer`
* Fix the readme in `dmerejkowsky/ruplacer`

By following this naming convention, we would have two options to install `ruplacer`, that we can document in the readmes:

```shell
# Option #1 - fully qualified formula name
brew install dmerejkowsky/ruplacer/ruplacer

# Option #2 - classic tap registration
brew tap dmerejkowsky/ruplacer
brew install ruplacer
```

Option #1 works because of a naming convention [described here](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#installing):

> If it’s on GitHub, users can install any of your formulae with `brew install user/repo/formula`. Homebrew will automatically add your `github.com/user/homebrew-repo` tap before installing the formula. `user/repo/formula` points to the `github.com/user/homebrew-repo/**/formula.rb` file here.

Option #2 works in the traditional explicit way of registering a tap [described here](https://docs.brew.sh/Taps#the-brew-tap-command).

We could also document how to remove the previous outdated tap (mentioned here: https://github.com/dmerejkowsky/homebrew-repo/pull/12#issuecomment-1082738568).

What do you think?

**Comment by maximerety** [comment]
☝️  Ping @dmerejkowsky.

The current [dmerejkowsky/homebrew-repo](https://github.com/dmerejkowsky/homebrew-repo) is not "brew-idiomatic", should we fix it or discard this idea?

**Pull request closed without merging**
