### PR TITLE
fix(API): add missing FilePatcher API

### PR DESCRIPTION
**Pull request by GreatestOfAllTimee**
Refs - https://github.com/dmerejkowsky/ruplacer/discussions/76#discussioncomment-2125141

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
Tests are failing. Here's a fix:

```
-/// let file = PathBuf::from("data.txt");
+/// let file = PathBuf::from("tests/data/top.txt");
```

Not sure this is the way to go, though. It's weird to see something about `tests/data` in the doc test ...

**Comment by dmerejkowsky** [comment]
What do you think about using a `data.txt` instead, like so:

```rust
/// Run replacement query on a given file
///
/// Example, assuming the `data.txt` file contains 'This is my old car'
/// ```rust
/// use ruplacer::{FilePatcher, Query};
/// use std::path::PathBuf;
///
/// # std::fs::write("data.txt", "This is my old car.").unwrap();
/// let file = PathBuf::from("data.txt");
/// let query = Query::substring("old", "new");
/// let file_patcher = FilePatcher::new(&file, &query).unwrap();
/// file_patcher.unwrap().run().unwrap();
///
/// let new_contents = std::fs::read_to_string("data.txt").unwrap();
/// assert_eq!(new_contents, "This is my new car.");
/// ```
```

**Comment by GreatestOfAllTimee** [comment]
> Tests are failing. Here's a fix:
> 
> ```
> -/// let file = PathBuf::from("data.txt");
> +/// let file = PathBuf::from("tests/data/top.txt");
> ```
> 

I just know that code block on crates docs rely on repo dirs/files. -- Intelligent AI nowdays.

**Comment by dmerejkowsky** [comment]
Superseded by #79

**Pull request closed without merging**
